from tkinter import filedialog
from tkinter import *
#root=Tk()
#root.title("hello")
#top=Toplevel()
#top.title("python")
#root.iconify()
#top.mainloop()
#print()
#handlepad
#handlesize
#add(child,options)
#get(startindex,)
#print()
#m1=PanedWindow()
#m1.pack(fill=BOTH,expand=1)
#left=Entry(m1,bd=5)
#m1.add(left)
#m2=PanedWindow(m1,orient=VERTICAL)
#m1.add(m2)
#top=Scale(m2,orient=HORIZONTAL)
#m2.add(top)
#bottom=Button(m2,text="OK")
#m2.add(bottom)
#mainloop()
#print()
#root=Tk()
#labelframe=LabelFrame(root,labelanchor='sw',text="this is a LabelFrame",highlightbackground='red',highlightcolor='yellow')
#labelframe.pack(fill="both",expand="yes")
#left=Label(labelframe,text="inside the LabelFrame")
#left.pack()
#mainloop()
#print()
root=Tk()
#frame=Frame(root)
#frame.pack()
#bottomframe=Frame(root)
#bottomframe.pack(side=BOTTOM)
#redbutton=Button(frame,text="Red",fg="red")
#redbutton.pack(side=LEFT)
#greenbutton=Button(frame,text="green",fg="green")
#greenbutton.pack(side=LEFT)
#bluebutton=Button(frame,text="blue",fg="blue")
#bluebutton.pack(side=LEFT)
#yellowbutton=Button(frame,text="yellow",fg="yellow")
#yellowbutton.pack(side=LEFT)
#pinkbutton=Button(frame,text="pink",fg="pink")
#pinkbutton.pack(side=LEFT)
#mainloop()
#print()
#root.filename=filedialog.asksaveasfilename(initialdir="/",title="selct file",filetypes=(("python files","*.py"),("all files","*.*")))
#print(root.filename)
#mainloop()
#root.filename=filedialog.askopenfilename(initialdir="/",title="selct file",filetypes=(("python files","*.py"),("all files","*.*")))
#print(root.filename)
#mainloop()
#print

root.directory=filedialog.askdirectory()
print(root.directory)