import numpy as np 
from numpy.core.multiarray import ndarray
a=np.array([1,2,3])
print(a)
a=np.array([(1,2,3),(4,5,6)])
print(a)
a=np.array([1,2,3,4,5],ndmin=2)
print(a)
a=np.array((1,2,3),dtype=complex)
print(a)
list2=[[0,1,2],[3,4,5],[6,7,8]]
arr2d=np.array(list2)
print(arr2d)
arr2d_f=np.array(list2,dtype='float')
print(arr2d_f)
arr=arr2d_f.astype('int')
print(arr)
arr1=arr2d_f.astype('int').astype('str')
print(arr1)
arr2d_b=np.array([1,0,10],dtype='bool')
print(arr2d_b)
print(type(arr2d_b))
arr1d_obj=np.array([1,'a'],dtype='object')
print(arr1d_obj)
print(type(arr1d_obj))
arr1d_obj=arr1d_obj.tolist()
print(arr1d_obj)
print(type(arr1d_obj))