import numpy as np 
arr=np.arange(10)
print(arr)
print("the shuffled array is")
np.random.shuffle(arr)
print(arr)
arr=np.arange(10)
print(arr)
print("the permuted array is")
print(np.random.permutation(10))
print(np.random.permutation([1,4,9,12,15]))
arr=np.arange(9).reshape((3,3))
print(arr)
print(np.random.permutation(arr))