import numpy as np 
arr=np.array([[0,1,2],[3,4,5],[6,7,8]])
print(arr)
print("the maximum is")
print(arr.max())
print("the mimimum is")
print(arr.min())
print("the index of maximum element is")
print(arr.argmax())
print("the index of minimum element is")
print(arr.argmin())
print("the maximum across axis 1 is")
print(arr.max(axis=1))
print("the minimum across axis 1 is")
print(arr.min(axis=1))
print("the index of maximum element across axis 1 is")
print(arr.argmax(axis=1))
print("the index of minimum element across axis 1 is")
print(arr.argmin(axis=1))