import pandas as pd 
import numpy as np 
print("AXES")
df=pd.DataFrame({'col1':[1,2],'col2':[3,4]})
print(df.axes)
print("DATA TYPES")
df=pd.DataFrame({'float':[1.0],'int':[1],'datatime':[pd.Timestamp('20190102')]
,'string':['foo']})
print(df.dtypes)
print("CHECK IF DATAFRAME IS EMPTY")
df_empty=pd.DataFrame({'A':[]})
print(df_empty)
print(df_empty.empty)
print("DIMENSIONS")
s=pd.Series({'a':1,'b':2,'c':3})
print(s.ndim)
df=pd.DataFrame({'col1':[1,2],'col2':[3,4]})
print(df.ndim)
print("SIZE")
s=pd.Series({'a':1,'b':2,'c':3})
print(s.size)
df=pd.DataFrame({'col1':[1,2],'col2':[3,4]})
print(df.size)
print("VALUES")
df=pd.DataFrame({'age':[3,29],'height':[94,170],'weight':[31,115]})
print(df.values)
df2=pd.DataFrame([('parrot',24.0,'second'),('lion',80.5,1),('monkey',np.nan,
None)],columns=('name','max_speed','rank'))
print(df2.values)
print("HEAD")
df=pd.DataFrame({'animal':['alligator','bee','falcon','lion','monkey',
'parrot','shark','whale','zebra']})
print(df.head())
print("TAIL")
print(df.tail())