import pandas as pd 
import numpy as np
d={'name':['Alisa','Bobby','cathrine','Madonna','Rocky','sebastian','jaqluine',
'Rahul','David','Andrew','Ajay','Teresa'],
'score1':[62,47,55,74,31,77,85,63,42,32,71,57],
'score2':[89,87,67,55,47,72,76,79,44,92,99,69],
'score3':[56,86,77,45,73,62,74,89,71,67,97,68],
'score4':[79,57,67,85,47,72,76,79,44,92,100,69],
'score5':[46,46,77,35,73,62,74,89,71,67,96,68]}
df=pd.DataFrame(d)
print(df)
print("SUM")
print(df.sum())
print("SUM COLUMN WISE")
print(df.sum(axis=0))
print("SUM ROW WISE")
print(df.sum(axis=1))
print("SPECIFIC COLUMN WISE")
print(df.loc[:,"score1"].sum())
print(df.loc[:,"score2"].sum())
print(df.loc[:,"score3"].sum())
print(df.loc[:,"score4"].sum())
print(df.loc[:,"score5"].sum())
df=pd.DataFrame(d)
print(df)
print("MEAN")
print(df.mean())
print("MEAN COLUMN WISE")
print(df.mean(axis=0))
print("MEAN ROW WISE")
print(df.mean(axis=1))
print("SPECIFIC COLUMN MEAN")
print(df.loc[:,"score1"].mean())
print(df.loc[:,"score2"].mean())
print(df.loc[:,"score3"].mean())
print("MEDIAN")
print(df.median())
print("MEDIAN COLUMN WISE")
print(df.median(axis=0))
print("MEDIAN ROW WISE")
print(df.median(axis=1))
print("SPECIFIC COLUMN MEDIAN")
print(df.loc[:,"score1"].median())
print(df.loc[:,"score2"].median())
print(df.loc[:,"score3"].median())
print("MODE")
print(df.mode())
print("MODE COLUMN WISE")
print(df.mode(axis=0))
print("MODE ROW WISE")
print(df.mode(axis=1))
print("SPECIFIC COLUMN MODE")
print(df.loc[:,"score1"].mode())
print(df.loc[:,"score2"].mode())
print(df.loc[:,"score3"].mode())
print("STANDARD DEVIATION")
print(df.std())
print("STD COLUMN WISE")
print(df.std(axis=0))
print("STD ROW WISE")
print(df.std(axis=1))
print("SPECIFIC COLUMN STD")
print(df.loc[:,"score1"].std())
print(df.loc[:,"score2"].std())
print(df.loc[:,"score3"].std())