import numpy as np 
names=np.array(['bob','joe','will','bob','joe','will','doe','jane'])
print(names)
print("the unique values are")
print(np.unique(names))
ints=np.array([[3,2,1],[2,3,8],[9,0,8]])
print(ints)
print("the unique values are")
print(np.unique(ints))
ints2=np.array([[1,2,1],[2,3,4],[9,0,6]])
print("the intersect values are")
print(np.intersect1d(ints,ints2))
print("the union of the array are")
print(np.union1d(ints,ints2))
print("the set difference of arrays are")
print(np.setdiff1d(ints,ints2))
print("the symmetric difference of array is")
print(np.setxor1d(ints,ints2))
print("the elment of ints present in ints2 is")
print(np.in1d(ints,ints2))
