import re
result=re.match(r'AV','AV Analytics vidhya AV')
print(result)
print(result.group(0))
result=re.match(r'Analytics','AV Analytics vidhya AV')
print(result)
result=re.match(r'AV','AV Analytics vidhya AV')
print(result.start())
print(result.end())
result=re.match(r'Analytics','AV Analytics vidhya AV')
#print(result.group(0))
result=re.findall(r'Av','AV Analytics vidhya AV')
print(result)
result=re.split(r'y','Analytics')
print(result)
result=re.split(r'i','Analytics vidhya')
print(result)
result=re.findall(r'.','AV is largest Analytics community of india')
print(result)
result=re.findall(r'\w','AV is largest Analytics community of india')
print(result)
result=re.findall(r'\w*','AV is largest Analytics community of india')
print(result)
result=re.findall(r'\w+','AV is largest Analytics community of india')
print(result)
result=re.findall(r'^\w+','AV is largest Analytics community of india')
print(result)
result=re.findall(r'\w+$','AV is largest Analytics community of india')
print(result)
result=re.findall(r'\w\w','AV is largest Analytics community of india')
print(result)
result=re.findall(r'\b\w.','AV is largest Analytics community of india')
print(result)
result=re.findall(r'\B\w.','AV is largest Analytics community of india')
print(result)
result=re.findall(r'@\w+','abc.test@gmail.com,xyz@test.in,test.first@analyticsvidhya.com,first.test@rest.biz')
print(result)
result=re.findall(r'@\w+.\w+','abc.test@gmail.com,xyz@test.in,test.first@analyticsvidhya.com,first.test@rest.biz')
print(result)
result=re.findall(r'@\w+.(\w+)','abc.test@gmail.com,xyz@test.in,test.first@analyticsvidhya.com,first.test@rest.biz')
print(result)
result=re.findall(r'\d{2}-\d{2}-\d{4}','Amit 34-3456 12-05-2007,xyz 56-4532 11-11-2011,ABC 67-8945 12-01-2009')
print(result)
result=re.findall(r'\b[aeiouAEIOU]\w+','AV is largest Analytics community of india')
print(result)


