from tkinter import *
def donothing():
    filewin=Toplevel(root)
    button=Button(filewin,text="do nothing button")
    button.pack()
root=Tk()
menubar=Menu(root)
filemenu=Menu(menubar,tearoff=0)
filemenu.add_command(label="new",command=donothing)
filemenu.add_command(label="open",command=donothing)
filemenu.add_command(label="save",command=donothing)
filemenu.add_command(label="save as...",command=donothing)
filemenu.add_command(label="close",command=donothing)
filemenu.add_separator()
filemenu.add_command(label="exit",command=root.quit)
filemenu.add_cascade(label="file",menu=filemenu)
editmenu=Menu(menubar,tearoff=0)
editmenu.add_command(label="undo",command=donothing)
editmenu.add_separator()
editmenu.add_command(label="cut",command=donothing)
editmenu.add_command(label="copy",command=donothing)
editmenu.add_command(label="paste",command=donothing)
editmenu.add_command(label="delete",command=donothing)
editmenu.add_command(label="select all",command=donothing)
menubar.add_cascade(label="edit",menu=editmenu)
helpmenu=Menu(menubar,tearoff=0)
helpmenu.add_command(label="help index",command=donothing)
helpmenu.add_command(label="about...",command=donothing)
menubar.add_cascade(label="help",menu=helpmenu)
root.config(menu=menubar)
root.mainloop() 