from tkinter import *
root=Tk()
text=Text(root,spacing1=5,spacing2=5,spacing3=5)
text.insert(INSERT,"hello.....")
text.insert(END,"bye bye.....")
text.pack()
text.tag_add("here","1.0","1.4")
text.tag_add("start","1.8","1.13")
text.tag_config("here",background="yellow",foreground="pink")
text.tag_config("start",background="pink",foreground="green")
root.mainloop()