import tkinter as tk
print('hello')
#place
#grid
#pack
#mainloop()
#w=label(master,option,...)
#values 
#w=Button(master,option=value,...)
#activebaground
#image
#w=checkbutton(master,option,...)
#offvalue
#onvalue
#state
w=canvas(master,option=value,...)
confine
height
scrollregion
arc=canvas.create_arc(coord,start=0,extend=150,fill="blue")
image=canvas.craete_image(50,50,anchor=NE,image=filename)
line=canvas.create_line(x0,y0,x1,y1,...,xn,yn,options)
oval=canvas.create_oval(x0,y0,x1,y1,options)
oval=canvas.create_polygon(x0,y0,x1,y1,options)
