from tkinter import *

rt = Tk()
rt.title('Registration Form')
rt.geometry('300x300')
rt.configure(background = 'light green')
lb = Label(rt, text = 'Form', bg = 'light green').grid(row = 0, column = 3)
lb1 = Label(rt, text = 'Name', bg = 'light green').grid(row = 1, column = 1)
entry1 = Entry(rt, justify  = RIGHT).grid(row = 1, column = 6)
lb2 = Label(rt, text = 'Course', bg = 'light green').grid(row = 2, column = 1)
entry2 = Entry(rt, justify = RIGHT).grid(row = 2, column = 6)
lb3 = Label(rt, text = 'Semester', bg = 'light green').grid(row = 3, column = 1)
entry3 = Entry(rt, justify = RIGHT).grid(row = 3, column = 6)
lb4 = Label(rt, text = 'Form No.', bg = 'light green').grid(row = 4, column = 1)
entry4 = Entry(rt, justify = RIGHT).grid(row = 4, column = 6)
lb5 = Label(rt, text = 'Contact No.', bg = 'light green').grid(row = 5, column = 1)
entry5 = Entry(rt, justify = RIGHT).grid(row = 5, column = 6)
lb6 = Label(rt, text = 'E-mail ID', bg = 'light green').grid(row = 6, column = 1)
entry6 = Entry(rt, justify = RIGHT).grid(row = 6, column = 6)
lb7 = Label(rt, text = 'Address', bg = 'light green').grid(row = 7, column = 1)
entry7 = Entry(rt, justify = RIGHT).grid(row = 7, column = 6)
b = Button(rt, text = 'Submit', bg = 'red', fg = 'black').grid(row = 8, column = 5)
mainloop()