from tkinter import *
rt = Tk() 
frame = Frame(rt) 
frame.pack() 
bottomframe = Frame(rt) 
bottomframe.pack( side = BOTTOM ) 
redbutton = Label(frame, text = 'name', fg ='red') 
redbutton.pack( side = LEFT) 
entry1 = Entry(rt, justify  = RIGHT).pack(side=LEFT)
#b1 = Label(rt, text = 'Name', bg = 'light green').pack(side=LEFT)
#entry1 = Entry(rt, justify  = RIGHT).pack(side=LEFT)
greenbutton = Label(frame, text = 'quantity', fg='brown').pack(side=LEFT)
#greenbutton.pack( side = LEFT ) 
entry2 = Entry(rt, justify  = RIGHT).pack(side=LEFT)
bluebutton = Button(frame, text ='insert', fg ='blue').pack(side=LEFT) 
#bluebutton.pack( side = LEFT ) 
entry3 = Entry(rt, justify  = RIGHT).pack(side=LEFT)
blackbutton = Button(bottomframe, text ='Remove', fg ='black') 
blackbutton.pack( side = BOTTOM) 
#root.mainloop() 
Lb = Listbox(rt) 
Lb.insert(1,'python','1')
Lb.insert(2, 'Java','9') 
Lb.insert(3, 'C++') 
Lb.insert(4, 'Any other') 
Lb.pack() 
lb=Listbox(rt)
Lb.insert(1,'5')
Lb.insert(2,'4')
Lb.insert(3,'8')
Lb.insert(4,'2')
Lb.pack()
rt.mainloop() 
